### ISSUE TITLE
Results hidden by URL tooltip when scrolling down with keys

### ISSUE THREAD

**Issue by Otiel** [infokiller/google-search-navigator#42]
When using the shortcuts (for instance <kbd>↓</kbd>) to navigate the links, the URL tooltip is hiding the result. See gif below.

![bug](https://user-images.githubusercontent.com/3851902/37758675-54c7c528-2db1-11e8-828c-d5a42bf4ffb5.gif)

It would be nice if the page was scrolled down enough to show the whole result:
* Title
* Link
* Description

**Comment by mancze** [comment]
It's Firefox, right? Unfortunately this is browser's behavior. The same happens when you cycle through results via `tab`. I think it would be worth report it to Mozilla directly.

I don't recall this happening before. Perhaps it might be bug introduced in some late versions? On the other side I hardly ever loop the results below the fold, so... :)

But as you suggested, scrolling down to show whole result including description would be nice and it would be a workaround.

**Comment by Otiel** [comment]
Yes, Firefox 59.0.1.

I understand it's Firefox behavior to show the URL tooltip on the page. I'm not blaming this. In fact, when using the mouse, Firefox displays the URL tooltip on the right/left depending on the position of the hyperlink in order to avoid hiding it.

My request is to scroll down a little bit more to show the whole result, and that will also fix this "issue". 😃
