### ISSUE TITLE
Extension requires permission to read browser history

### ISSUE THREAD

**Issue by Mastergalen** [infokiller/google-search-navigator#53]
In v0.2.8 the extension is requesting permission to read my browser history.

Why is this necessary?

**Comment by beracira** [comment]
i just quickly went over the [manifest file](https://github.com/infokiller/google-search-navigator/commit/c02163bf66da53db3573081ebb7e17c470e67547#diff-051a8a7bcae8db1e4cee8eb09b52e619), I think this is the commit where the new permission is introduced. 

it seems that the "tabs" permission is requested to implement the new feature mentioned in the doc, which is to open a new tab in background. 

in the [official documentation](https://developer.chrome.com/extensions/tabs), it says,

> The majority of the chrome.tabs API can be used without declaring any permission. However, the "tabs" permission is required in order to populate the url, title, and favIconUrl properties of Tab. 

i haven't seen any code snippet where the extension tries to read current open tabs or the browsing history. it looks like chrome gives the warning because your browsing history is basically made up of the tabs you open. 

despite this being an arguably API design flaw from Google side, i will still recommend the author to remove this feature if there is no way around requesting the permission, since it has caused loss of users and potential harm to the project's reputation. (store review page)

btw, isn't the "open in a new tab" thing already available? (if you just do ctrl + enter), i guess the purpose  of this change is to give the ability to reassign the shortcut?

**Comment by beracira** [comment]
sorry i was wrong about the permission part. it seems that new tabs can be created with desired url even after i removed the "tabs" permission. so this should definitely be removed to avoid further confusion. (tested on chrome version 66 on linux).

i'm going to make a pull request to remove the line.

**Comment by medizinmensch** [comment]
hi folks!
I just want to emphasize that :
1. I love the google-search-navigator and
2. I realy disregard the permission change

Thank you @beracira for making the pull request! ❤️

**Comment by infokiller** [comment]
First I'd like to apologize for this confusing warning and clarify that this extension certainly **does not read any of your browsing history**.
One of the pros of being open source is that any user can easily verify that the code doesn't do anything malicious.

It seems the issue was introduced in PR #37 which actually requires the "tabs" permission.

Thanks for investigating @beracira !
I will merge your PR and test it to release a new version. If the "open tab in background" feature will no longer work it will be unfortunate, but indeed better than this warning.

**Comment by infokiller** [comment]
Update: I started publishing the new version of the extension (0.2.9) which removes the "tabs" permission following the PR of @beracira .

It should be available in the webstore in 1 hour, and will hopefully be updated for users very soon.

**Comment by panozzaj** [comment]
Thanks for the quick turnaround, I use this tool all of the time and was confused by the new permissions requested. This seems like it should reduce confusion overall!

**Comment by beracira** [comment]
@infokiller thanks for the quick response! it seems that the issue has been resolved. and the new feature is also working just fine.
